import { useState } from 'react';
import { FileText, Loader2 } from 'lucide-react';

export default function DailyBrief() {
  const [generating, setGenerating] = useState(false);

  const generate = async () => {
    setGenerating(true);
    try {
      const [stocksRes, pricesRes, noticesRes, etfRes, lbmaRes] = await Promise.all([
        fetch('/api/cme/latest-stocks?metal=GOLD').then(r => r.json()),
        fetch('/api/prices/latest?metal=GOLD').then(r => r.json()),
        fetch('/api/cme/latest-notices?metal=GOLD').then(r => r.json()),
        fetch('/api/etf/holdings').then(r => r.json()).catch(() => null),
        fetch('/api/lbma/latest').then(r => r.json()).catch(() => null),
      ]);

      const stocks = Array.isArray(stocksRes) ? stocksRes : [];
      const latest = stocks.length > 0 ? stocks[stocks.length - 1] : null;
      const prices = pricesRes?.prices ?? [];
      const todayPrice = prices[0];
      const notices = Array.isArray(noticesRes) ? noticesRes : [];
      const totalStopped = notices.reduce((s: number, n: any) => s + (n.stopped ?? 0), 0);
      const totalIssued = notices.reduce((s: number, n: any) => s + (n.issued ?? 0), 0);

      // Top buyers/sellers
      const topBuyers = notices
        .filter((n: any) => n.stopped > 0)
        .sort((a: any, b: any) => b.stopped - a.stopped)
        .slice(0, 5);
      const topSellers = notices
        .filter((n: any) => n.issued > 0)
        .sort((a: any, b: any) => b.issued - a.issued)
        .slice(0, 5);

      const etfFunds = etfRes?.funds ?? [];
      const lbmaVaults = lbmaRes?.vaults ?? [];
      const lbmaLatest = lbmaVaults[0];

      const today = new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });

      // Compute signal
      let signal = 'QUIET';
      if (prices.length >= 3 && latest) {
        const avgPct = prices.slice(0, 3).reduce((s: number, p: any) => s + (p.changePct ?? 0), 0) / 3;
        const last3Stocks = stocks.slice(-3);
        const totalReg = last3Stocks.reduce((s: number, st: any) => s + (st.daily_change_registered ?? 0), 0);
        if (Math.abs(avgPct) >= 0.1 || Math.abs(totalReg) >= 5000) {
          const up = avgPct > 0;
          const sDown = totalReg < 0;
          const sUp = totalReg > 0;
          if (up && sDown) signal = 'BULLISH';
          else if (!up && sUp) signal = 'MIXED';
          else if (up && sUp) signal = 'CAUTIOUS';
          else if (!up && sDown) signal = 'BEARISH';
        }
      }

      const html = `<!DOCTYPE html>
<html><head>
<title>Gold Market Daily Brief — ${today}</title>
<style>
  body { font-family: 'Helvetica Neue', Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px 30px; color: #1a1a1a; font-size: 13px; line-height: 1.6; }
  h1 { font-size: 22px; margin-bottom: 4px; }
  h2 { font-size: 16px; margin-top: 24px; margin-bottom: 8px; border-bottom: 1px solid #e5e5e5; padding-bottom: 4px; }
  .subtitle { color: #666; font-size: 12px; margin-bottom: 20px; }
  .signal { display: inline-block; padding: 4px 12px; border-radius: 4px; font-weight: bold; font-size: 13px; }
  .signal.BULLISH { background: #d1fae5; color: #065f46; }
  .signal.BEARISH { background: #fee2e2; color: #991b1b; }
  .signal.CAUTIOUS { background: #fef3c7; color: #92400e; }
  .signal.MIXED { background: #dbeafe; color: #1e40af; }
  .signal.QUIET { background: #f4f4f5; color: #52525b; }
  table { width: 100%; border-collapse: collapse; margin: 8px 0 16px; }
  th, td { text-align: left; padding: 6px 10px; border-bottom: 1px solid #e5e5e5; font-size: 12px; }
  th { font-weight: 600; color: #666; }
  .metric { display: inline-block; min-width: 180px; margin: 6px 12px 6px 0; }
  .metric-label { font-size: 10px; color: #888; text-transform: uppercase; letter-spacing: 0.5px; }
  .metric-value { font-size: 18px; font-weight: 700; }
  .positive { color: #059669; }
  .negative { color: #dc2626; }
  .footer { margin-top: 30px; padding-top: 12px; border-top: 1px solid #e5e5e5; font-size: 10px; color: #999; }
  @media print { body { padding: 20px; } }
</style>
</head><body>
<h1>Gold Market Daily Brief</h1>
<p class="subtitle">${today} | Generated by BullionTrack</p>

<div>
  <span class="signal ${signal}">Signal: ${signal}</span>
</div>

<h2>Price</h2>
<div>
  <div class="metric">
    <div class="metric-label">Settlement</div>
    <div class="metric-value">${todayPrice ? `$${todayPrice.close.toLocaleString()}` : '—'}</div>
  </div>
  <div class="metric">
    <div class="metric-label">Daily Change</div>
    <div class="metric-value ${(todayPrice?.changePct ?? 0) >= 0 ? 'positive' : 'negative'}">
      ${todayPrice?.changePct != null ? `${todayPrice.changePct > 0 ? '+' : ''}${todayPrice.changePct.toFixed(2)}% ($${(todayPrice.changeUsd ?? 0).toFixed(2)})` : '—'}
    </div>
  </div>
</div>

<h2>COMEX Warehouse</h2>
<div>
  <div class="metric">
    <div class="metric-label">Registered</div>
    <div class="metric-value">${latest ? `${(latest.registered_oz / 1_000_000).toFixed(2)}M oz` : '—'}</div>
  </div>
  <div class="metric">
    <div class="metric-label">Reg. Daily Δ</div>
    <div class="metric-value ${(latest?.daily_change_registered ?? 0) >= 0 ? 'positive' : 'negative'}">
      ${latest?.daily_change_registered != null ? `${latest.daily_change_registered > 0 ? '+' : ''}${(latest.daily_change_registered / 1000).toFixed(1)}k oz` : '—'}
    </div>
  </div>
  <div class="metric">
    <div class="metric-label">Total</div>
    <div class="metric-value">${latest ? `${(latest.total_oz / 1_000_000).toFixed(2)}M oz` : '—'}</div>
  </div>
</div>

<h2>Deliveries</h2>
<div>
  <div class="metric">
    <div class="metric-label">Contracts Stopped</div>
    <div class="metric-value">${totalStopped.toLocaleString()}</div>
  </div>
  <div class="metric">
    <div class="metric-label">Contracts Issued</div>
    <div class="metric-value">${totalIssued.toLocaleString()}</div>
  </div>
</div>

${topBuyers.length > 0 ? `
<h2>Top Buyers (Stopping)</h2>
<table>
  <tr><th>Firm</th><th>Contracts</th></tr>
  ${topBuyers.map((b: any) => `<tr><td>${b.firm}</td><td>${b.stopped}</td></tr>`).join('')}
</table>` : ''}

${topSellers.length > 0 ? `
<h2>Top Sellers (Issuing)</h2>
<table>
  <tr><th>Firm</th><th>Contracts</th></tr>
  ${topSellers.map((s: any) => `<tr><td>${s.firm}</td><td>${s.issued}</td></tr>`).join('')}
</table>` : ''}

${etfFunds.length > 0 ? `
<h2>ETF Holdings</h2>
<table>
  <tr><th>Fund</th><th>Tonnes</th><th>Monthly Δ</th></tr>
  ${etfFunds.map((f: any) => `<tr><td>${f.ticker} (${f.name})</td><td>${f.tonnes.toFixed(1)}</td><td>${f.changeTonnes != null ? `${f.changeTonnes > 0 ? '+' : ''}${f.changeTonnes.toFixed(1)}` : '—'}</td></tr>`).join('')}
</table>` : ''}

${lbmaLatest ? `
<h2>London Vault (LBMA)</h2>
<div>
  <div class="metric">
    <div class="metric-label">Gold Holdings</div>
    <div class="metric-value">${(lbmaLatest.goldOz / 1_000_000).toFixed(1)}M oz (${lbmaLatest.goldTonnes.toLocaleString()}t)</div>
  </div>
  <div class="metric">
    <div class="metric-label">Latest Month</div>
    <div class="metric-value">${lbmaLatest.month}</div>
  </div>
</div>` : ''}

<div class="footer">
  This report is auto-generated from CME, LBMA, and WGC data by BullionTrack. For informational purposes only — not financial advice.
</div>
</body></html>`;

      const w = window.open('', '_blank');
      if (w) {
        w.document.write(html);
        w.document.close();
        setTimeout(() => w.print(), 500);
      }
    } catch (e) {
      console.error('Brief generation failed:', e);
    } finally {
      setGenerating(false);
    }
  };

  return (
    <button
      onClick={generate}
      disabled={generating}
      className="flex items-center gap-2 px-3 py-1.5 rounded-lg text-[10px] font-bold uppercase tracking-wider transition-all bg-zinc-900 text-zinc-400 border border-zinc-800 hover:text-zinc-100 disabled:opacity-50"
    >
      {generating ? <Loader2 className="w-3 h-3 animate-spin" /> : <FileText className="w-3 h-3" />}
      Daily Brief
    </button>
  );
}
